# Generated by Django 5.1.2 on 2024-10-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_nombre_boleta_name_payment_delete_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_due',
            field=models.DateField(blank=True, null=True),
        ),
    ]
